### PR TITLE
Add /config/environment.sh which can set environment variables

### PR DESCRIPTION
**Pull request by LunNova**
Fix for http://lime-technology.com/forum/index.php?topic=45839.msg441207#msg441207

This will allow changing JVM  options, making jenkins run in a subdirectory and other advanced settings as described here: https://wiki.jenkins-ci.org/display/JENKINS/Features+controlled+by+system+properties

### CODE REVIEW

**Comment by LunNova** [comment]
Hi,

Any chance of getting this merged if I update it to match your changes (modifying `setup/nobody/start.sh` instead)?

edit: now updated

**Comment by binhex** [comment]
Looking at the wiki page this looks like Java options your passing not env vars, so I think I would need to come up with a method of adding these if specified to the command line, do you agree?

**Comment by LunNova** [comment]
If the file `/config/environment.sh` exists, it will be sourced. I can put this:

```
export JAVA_OPTS=-Dhudson.security.csrf.requestfield=X-Jenkins-Crumb
```

in that file to add the `-Dhudson.security.csrf.requestfield=X-Jenkins-Crumb` setting. It could also export any of the other variables used eg `JENKINS_OPTs`.

(it was broken, I had the added line in the wrong place so it would also need to redefine `JENKINS_COMMAND_LINE` but that's sorted now)

**Comment by binhex** [comment]
hi, i have incorporated this by allowing java_opts and java_args to be defined via docker run command, please see the readme for details.

**Comment by LunNova** [comment]
Thanks! That's a better solution than what I wanted.

**Pull request closed without merging**
