### PR TITLE
Add OpenSSH to default installed packages

### LINKED ISSUE #4: ssh missing
git requires ssh for ssh repositories. Shouldn't this be included in the image or have an option for it to be included ?

### PR DESCRIPTION
**Pull request by mattheworres**
Fixes #4 (hopefully)

This seems pretty straight forward of an addition, but outside of having actually run `pacman -S openssh` on my own container based on your image, I imagine this would work. Still, I'll welcome any advice or suggestions on how to more thoroughly test this.

Thanks for all of your work!

### CODE REVIEW

**Comment by mattheworres** [comment]
Actually, it'd be pretty helpful if we could instead just supply a list of Arch packages to automatically install for the container (though I do think OpenSSH makes sense to just be there, just like Git) - is this something we could maybe add to this container in a separate PR?

**Comment by mattheworres** [comment]
@binhex not sure if you saw this PR, but any feedback you could provide? Thank you!

**Comment by binhex** [comment]
sorry yes this did slip through the net, can you give me a bit more details on your propsed usage of openssh, afaik ssh is not required in order to run jobs on the server, or is this to allow connections to nodes?

**Comment by mattheworres** [comment]
> sorry yes this did slip through the net, can you give me a bit more details on your propsed usage of openssh, afaik ssh is not required in order to run jobs on the server, or is this to allow connections to nodes?

No apologies! So in order to pull repositories from Github via an SSH connection, the `openssh` package is required in order to give Jenkins the ability to complete the connection.

When I SSH into my container and manually install it, I can then pull my project repos from Github over SSH. Have been waiting to update my container because I didn't feel like going in and manually reinstalling it :)

**Review by binhex — APPROVED** [review]

**Comment by binhex** [comment]
merged, image building...

**Pull request merged**
